version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: backend
    build:
      context: ../Viverabackend
      dockerfile: Dockerfile

    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/

    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./frontend/build:/usr/share/nginx/html/

    depends_on:
      - backend
      - frontend

volumes:
  database:
  static_value:
  media_value: