# Generated by Django 4.2 on 2023-05-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldermodel',
            name='folder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
