# Generated by Django 4.2 on 2023-05-22 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0002_foldermodel_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetmodel',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_widget', to='widgets.foldermodel'),
        ),
    ]
