# Generated by Django 4.2 on 2023-05-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0003_alter_widgetmodel_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktopmodel',
            name='max_z_index',
            field=models.IntegerField(default=0),
        ),
    ]
