# Generated by Django 4.2 on 2023-04-26 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bufferuserwidgetmodel',
            name='widget_uuid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buffer_widget', to='widgets.widgetmodel'),
        ),
        migrations.AddField(
            model_name='bufferusersocketmodel',
            name='user_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socket_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
