# Generated by Django 4.2 on 2023-04-14 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BufferUserSocketModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('socket_id', models.CharField(max_length=100)),
                ('user_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socket_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
